services:
  - type: web
    name: medipredict
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn disease_app.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: disease_app.settings.production
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://*.onrender.com
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: DATABASE_URL
        fromDatabase:
          name: medipredict-db
          property: connectionString

databases:
  - name: medipredict-db
    databaseName: medipredict
    user: medipredict
    plan: free
