# Generated by Django 4.2.7 on 2026-02-06 12:38

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import prescriptions_app.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DrugInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("minor", "Minor"),
                            ("moderate", "Moderate"),
                            ("major", "Major"),
                            ("contraindicated", "Contraindicated"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("mechanism", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                ("reference", models.URLField(blank=True)),
                ("last_updated", models.DateField(auto_now=True)),
            ],
            options={
                "verbose_name": "Drug Interaction",
                "verbose_name_plural": "Drug Interactions",
                "ordering": ["severity", "medicine1__name"],
            },
        ),
        migrations.CreateModel(
            name="MedicationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("prescribed", "Prescribed"),
                            ("dispensed", "Dispensed"),
                            ("administered", "Administered"),
                            ("missed", "Missed Dose"),
                            ("stopped", "Stopped"),
                            ("changed", "Dosage Changed"),
                            ("refilled", "Refilled"),
                        ],
                        max_length=50,
                    ),
                ),
                ("details", models.TextField(blank=True)),
                ("dosage_taken", models.CharField(blank=True, max_length=100)),
                ("taken_at", models.DateTimeField(blank=True, null=True)),
                ("side_effects", models.TextField(blank=True)),
                (
                    "severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mild", "Mild"),
                            ("moderate", "Moderate"),
                            ("severe", "Severe"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "effectiveness_rating",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Medication History",
                "verbose_name_plural": "Medication History",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("generic_name", models.CharField(blank=True, max_length=200)),
                ("brand_name", models.CharField(blank=True, max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("antibiotic", "Antibiotic"),
                            ("analgesic", "Analgesic (Pain Reliever)"),
                            ("antihypertensive", "Antihypertensive"),
                            ("antidiabetic", "Antidiabetic"),
                            ("antiinflammatory", "Anti-inflammatory"),
                            ("antidepressant", "Antidepressant"),
                            ("antihistamine", "Antihistamine"),
                            ("vitamin", "Vitamin/Supplement"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "form",
                    models.CharField(
                        choices=[
                            ("tablet", "Tablet"),
                            ("capsule", "Capsule"),
                            ("syrup", "Syrup/Liquid"),
                            ("injection", "Injection"),
                            ("ointment", "Ointment/Cream"),
                            ("inhaler", "Inhaler"),
                            ("drops", "Drops"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "strength",
                    models.CharField(help_text="e.g., 500mg, 10mg/ml", max_length=100),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=200)),
                ("side_effects", models.TextField(blank=True)),
                ("contraindications", models.TextField(blank=True)),
                ("pregnancy_category", models.CharField(blank=True, max_length=10)),
                ("storage_instructions", models.TextField(blank=True)),
                ("requires_prescription", models.BooleanField(default=True)),
                ("is_controlled_substance", models.BooleanField(default=False)),
                (
                    "schedule",
                    models.CharField(
                        blank=True,
                        help_text="Drug schedule classification",
                        max_length=10,
                    ),
                ),
                (
                    "medicine_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="medicine_images/"
                    ),
                ),
                (
                    "leaflet",
                    models.FileField(
                        blank=True, null=True, upload_to="medicine_leaflets/"
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
                ("reorder_level", models.PositiveIntegerField(default=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Medicine",
                "verbose_name_plural": "Medicines",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Pharmacy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("opening_time", models.TimeField(default="09:00")),
                ("closing_time", models.TimeField(default="21:00")),
                ("is_24_hours", models.BooleanField(default=False)),
                ("delivers", models.BooleanField(default=False)),
                ("accepts_insurance", models.BooleanField(default=True)),
                ("has_compounding", models.BooleanField(default=False)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("license_number", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pharmacy",
                "verbose_name_plural": "Pharmacies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prescription_id",
                    models.CharField(
                        default=prescriptions_app.models.generate_prescription_id,
                        max_length=20,
                        unique=True,
                        verbose_name="Prescription ID",
                    ),
                ),
                ("diagnosis", models.TextField(blank=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional instructions for patient"
                    ),
                ),
                (
                    "prescription_type",
                    models.CharField(
                        choices=[
                            ("new", "New Prescription"),
                            ("refill", "Refill"),
                            ("emergency", "Emergency"),
                            ("chronic", "Chronic Condition"),
                            ("preventive", "Preventive"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("issue_date", models.DateField(default=django.utils.timezone.now)),
                ("valid_until", models.DateField()),
                ("refills_allowed", models.PositiveIntegerField(default=0)),
                ("refills_remaining", models.PositiveIntegerField(default=0)),
                (
                    "doctor_signature",
                    models.ImageField(blank=True, null=True, upload_to="signatures/"),
                ),
                (
                    "digital_signature_hash",
                    models.CharField(blank=True, max_length=255),
                ),
                ("pharmacy_notes", models.TextField(blank=True)),
                ("is_pharmacy_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Prescription",
                "verbose_name_plural": "Prescriptions",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("refill_due", "Refill Due"),
                            ("expiring_soon", "Prescription Expiring"),
                            ("interaction", "Drug Interaction"),
                            ("allergy", "Allergy Alert"),
                            ("dosage", "Dosage Alert"),
                            ("compliance", "Compliance Issue"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Prescription Alert",
                "verbose_name_plural": "Prescription Alerts",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dosage",
                    models.CharField(help_text="e.g., 1 tablet, 10ml", max_length=100),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("once_daily", "Once Daily"),
                            ("twice_daily", "Twice Daily"),
                            ("thrice_daily", "Three Times Daily"),
                            ("four_times_daily", "Four Times Daily"),
                            ("every_other_day", "Every Other Day"),
                            ("weekly", "Once Weekly"),
                            ("as_needed", "As Needed (PRN)"),
                            ("before_meal", "Before Meal"),
                            ("after_meal", "After Meal"),
                            ("at_bedtime", "At Bedtime"),
                        ],
                        default="once_daily",
                        max_length=20,
                    ),
                ),
                ("duration", models.PositiveIntegerField(default=7)),
                (
                    "duration_unit",
                    models.CharField(
                        choices=[
                            ("days", "Days"),
                            ("weeks", "Weeks"),
                            ("months", "Months"),
                            ("indefinite", "Until Finished"),
                        ],
                        default="days",
                        max_length=10,
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True, help_text="Specific instructions for this medicine"
                    ),
                ),
                ("take_with_food", models.BooleanField(default=False)),
                ("avoid_alcohol", models.BooleanField(default=False)),
                (
                    "specific_times",
                    models.CharField(
                        blank=True, help_text="e.g., 8:00, 20:00", max_length=200
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_dispensed", models.BooleanField(default=False)),
                ("dispensed_quantity", models.PositiveIntegerField(default=0)),
                ("dispensed_at", models.DateTimeField(blank=True, null=True)),
                ("allow_generic", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Prescription Item",
                "verbose_name_plural": "Prescription Items",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="RefillRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_date", models.DateTimeField(auto_now_add=True)),
                ("requested_refill_count", models.PositiveIntegerField(default=1)),
                ("reason", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("doctor_response", models.TextField(blank=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("pharmacy_notes", models.TextField(blank=True)),
                ("is_ready_for_pickup", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Refill Request",
                "verbose_name_plural": "Refill Requests",
                "ordering": ["-request_date"],
            },
        ),
    ]
