# Generated by Django 4.2.7 on 2026-02-06 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("prescriptions_app", "0001_initial"),
        ("consultations_app", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="refillrequest",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refill_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="refillrequest",
            name="prescription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refill_requests",
                to="prescriptions_app.prescription",
            ),
        ),
        migrations.AddField(
            model_name="refillrequest",
            name="responded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_refills",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="medicine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="prescriptions_app.medicine",
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="prescription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="prescriptions_app.prescription",
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="substituted_with",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="substituted_items",
                to="prescriptions_app.medicine",
            ),
        ),
        migrations.AddField(
            model_name="prescriptionalert",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescription_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="prescriptionalert",
            name="prescription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="prescriptions_app.prescription",
            ),
        ),
        migrations.AddField(
            model_name="prescriptionalert",
            name="related_interaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="prescriptions_app.druginteraction",
            ),
        ),
        migrations.AddField(
            model_name="prescriptionalert",
            name="related_medicine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="prescriptions_app.medicine",
            ),
        ),
        migrations.AddField(
            model_name="prescriptionalert",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="consultation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prescription_link",
                to="consultations_app.consultation",
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_prescriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_prescriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="pharmacy",
            index=models.Index(fields=["name"], name="prescriptio_name_e5f8f4_idx"),
        ),
        migrations.AddIndex(
            model_name="pharmacy",
            index=models.Index(
                fields=["is_verified"], name="prescriptio_is_veri_33c57b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicine",
            index=models.Index(fields=["name"], name="prescriptio_name_7743df_idx"),
        ),
        migrations.AddIndex(
            model_name="medicine",
            index=models.Index(
                fields=["category"], name="prescriptio_categor_ec41bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicine",
            index=models.Index(
                fields=["is_available"], name="prescriptio_is_avai_8ba370_idx"
            ),
        ),
        migrations.AddField(
            model_name="medicationhistory",
            name="administered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="administered_medications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="medicationhistory",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medication_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="medicationhistory",
            name="prescription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history_entries",
                to="prescriptions_app.prescription",
            ),
        ),
        migrations.AddField(
            model_name="medicationhistory",
            name="prescription_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="prescriptions_app.prescriptionitem",
            ),
        ),
        migrations.AddField(
            model_name="druginteraction",
            name="medicine1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interactions_as_first",
                to="prescriptions_app.medicine",
            ),
        ),
        migrations.AddField(
            model_name="druginteraction",
            name="medicine2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interactions_as_second",
                to="prescriptions_app.medicine",
            ),
        ),
        migrations.AddIndex(
            model_name="refillrequest",
            index=models.Index(
                fields=["prescription", "status"], name="prescriptio_prescri_02a1d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refillrequest",
            index=models.Index(
                fields=["patient", "status"], name="prescriptio_patient_109d4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescriptionalert",
            index=models.Index(
                fields=["patient", "is_read"], name="prescriptio_patient_de80a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescriptionalert",
            index=models.Index(
                fields=["alert_type", "priority"], name="prescriptio_alert_t_e4e750_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["prescription_id"], name="prescriptio_prescri_15fa73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["patient", "status"], name="prescriptio_patient_35365c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["doctor", "issue_date"], name="prescriptio_doctor__1b6802_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["valid_until", "status"], name="prescriptio_valid_u_29a304_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicationhistory",
            index=models.Index(
                fields=["patient", "recorded_at"], name="prescriptio_patient_5c3256_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicationhistory",
            index=models.Index(
                fields=["prescription", "action"], name="prescriptio_prescri_c8376f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="druginteraction",
            unique_together={("medicine1", "medicine2")},
        ),
    ]
