# Generated by Django 4.2.7 on 2026-02-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Notification Title"),
                ),
                ("message", models.TextField(verbose_name="Notification Message")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("system", "System Notification"),
                            ("prediction", "Prediction Result"),
                            ("appointment", "Appointment Reminder"),
                            ("prescription", "Prescription Update"),
                            ("security", "Security Alert"),
                            ("health_tip", "Health Tip"),
                            ("promotional", "Promotional"),
                        ],
                        default="system",
                        max_length=50,
                        verbose_name="Notification Type",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Priority",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Is Read")),
                (
                    "action_url",
                    models.URLField(blank=True, null=True, verbose_name="Action URL"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Additional Data"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Read At"),
                ),
                (
                    "scheduled_for",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Scheduled For"
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("push", "Push"),
                            ("sms", "SMS"),
                            ("in_app", "In-App"),
                        ],
                        max_length=20,
                        verbose_name="Delivery Method",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("read", "Read"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Delivery Status",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Error Message"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Sent At"),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Delivered At"
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Log",
                "verbose_name_plural": "Notification Logs",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Email Notifications"
                    ),
                ),
                (
                    "email_prediction_results",
                    models.BooleanField(
                        default=True, verbose_name="Prediction Results"
                    ),
                ),
                (
                    "email_appointment_reminders",
                    models.BooleanField(
                        default=True, verbose_name="Appointment Reminders"
                    ),
                ),
                (
                    "email_prescription_updates",
                    models.BooleanField(
                        default=True, verbose_name="Prescription Updates"
                    ),
                ),
                (
                    "email_security_alerts",
                    models.BooleanField(default=True, verbose_name="Security Alerts"),
                ),
                (
                    "email_promotional",
                    models.BooleanField(
                        default=False, verbose_name="Promotional Emails"
                    ),
                ),
                (
                    "push_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Push Notifications"
                    ),
                ),
                (
                    "push_prediction_results",
                    models.BooleanField(
                        default=True, verbose_name="Prediction Results"
                    ),
                ),
                (
                    "push_appointment_reminders",
                    models.BooleanField(
                        default=True, verbose_name="Appointment Reminders"
                    ),
                ),
                (
                    "sms_notifications",
                    models.BooleanField(
                        default=False, verbose_name="SMS Notifications"
                    ),
                ),
                (
                    "sms_important_alerts",
                    models.BooleanField(default=False, verbose_name="Important Alerts"),
                ),
                (
                    "notification_frequency",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediate"),
                            ("daily_digest", "Daily Digest"),
                            ("weekly_digest", "Weekly Digest"),
                        ],
                        default="immediate",
                        max_length=20,
                        verbose_name="Notification Frequency",
                    ),
                ),
                (
                    "do_not_disturb_start",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Do Not Disturb Start"
                    ),
                ),
                (
                    "do_not_disturb_end",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Do Not Disturb End"
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Template Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("email", "Email Template"),
                            ("push", "Push Notification Template"),
                            ("sms", "SMS Template"),
                            ("in_app", "In-App Notification Template"),
                        ],
                        max_length=20,
                        verbose_name="Template Type",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Subject"
                    ),
                ),
                ("body", models.TextField(verbose_name="Template Body")),
                (
                    "variables",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Template Variables"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Notification Template",
                "verbose_name_plural": "Notification Templates",
                "ordering": ["name"],
            },
        ),
    ]
