# Generated by Django 4.2.7 on 2026-02-06 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Key ID')),
                ('secret_key', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Secret Key')),
                ('name', models.CharField(max_length=100, verbose_name='API Key Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('rate_limit_per_minute', models.IntegerField(default=60, verbose_name='Requests per Minute')),
                ('rate_limit_per_hour', models.IntegerField(default=1000, verbose_name='Requests per Hour')),
                ('rate_limit_per_day', models.IntegerField(default=10000, verbose_name='Requests per Day')),
                ('allowed_ips', models.JSONField(blank=True, default=list, help_text='List of allowed IP addresses (empty for all)', verbose_name='Allowed IPs')),
                ('allowed_methods', models.CharField(default='["GET","POST","PUT","DELETE"]', help_text='List of allowed HTTP methods (JSON array)', max_length=255, verbose_name='Allowed Methods')),
                ('allowed_endpoints', models.TextField(blank=True, default='[]', help_text='List of allowed endpoints (JSON array, empty for all)', verbose_name='Allowed Endpoints')),
                ('requests_today', models.IntegerField(default=0, verbose_name='Requests Today')),
                ('total_requests', models.IntegerField(default=0, verbose_name='Total Requests')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Last Used')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True, verbose_name='API Version')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deprecated', models.BooleanField(default=False, verbose_name='Is Deprecated')),
                ('deprecation_date', models.DateField(blank=True, null=True, verbose_name='Deprecation Date')),
                ('sunset_date', models.DateField(blank=True, null=True, verbose_name='Sunset Date')),
                ('changelog', models.TextField(blank=True, verbose_name='Changelog')),
                ('documentation_url', models.URLField(blank=True, verbose_name='Documentation URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'API Version',
                'verbose_name_plural': 'API Versions',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='APIRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute_count', models.IntegerField(default=0, verbose_name='Minute Count')),
                ('hour_count', models.IntegerField(default=0, verbose_name='Hour Count')),
                ('day_count', models.IntegerField(default=0, verbose_name='Day Count')),
                ('minute_window_start', models.DateTimeField(auto_now_add=True, verbose_name='Minute Window Start')),
                ('hour_window_start', models.DateTimeField(auto_now_add=True, verbose_name='Hour Window Start')),
                ('day_window_start', models.DateTimeField(auto_now_add=True, verbose_name='Day Window Start')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('api_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rate_limit', to='api_app.apikey', verbose_name='API Key')),
            ],
            options={
                'verbose_name': 'API Rate Limit',
                'verbose_name_plural': 'API Rate Limits',
            },
        ),
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10, verbose_name='HTTP Method')),
                ('endpoint', models.CharField(max_length=500, verbose_name='Endpoint')),
                ('request_data', models.JSONField(blank=True, null=True, verbose_name='Request Data')),
                ('query_params', models.JSONField(blank=True, null=True, verbose_name='Query Parameters')),
                ('status_code', models.IntegerField(verbose_name='Status Code')),
                ('response_data', models.JSONField(blank=True, null=True, verbose_name='Response Data')),
                ('response_time', models.FloatField(verbose_name='Response Time (ms)')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('referer', models.URLField(blank=True, null=True, verbose_name='Referer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('api_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='api_app.apikey', verbose_name='API Key')),
            ],
            options={
                'verbose_name': 'API Log',
                'verbose_name_plural': 'API Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
