# Generated by Django 4.2.7 on 2026-02-06 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='apilog',
            index=models.Index(fields=['api_key', 'created_at'], name='api_app_api_api_key_210d7e_idx'),
        ),
        migrations.AddIndex(
            model_name='apilog',
            index=models.Index(fields=['status_code'], name='api_app_api_status__e0ee82_idx'),
        ),
        migrations.AddIndex(
            model_name='apilog',
            index=models.Index(fields=['endpoint'], name='api_app_api_endpoin_a85726_idx'),
        ),
        migrations.AddIndex(
            model_name='apilog',
            index=models.Index(fields=['ip_address'], name='api_app_api_ip_addr_334d83_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['key_id'], name='api_app_api_key_id_8130fe_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['user'], name='api_app_api_user_id_a10aa7_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['is_active'], name='api_app_api_is_acti_0d7762_idx'),
        ),
    ]
